account/urls.py
from django.urls import path, include
from .views import dashboard, register, edit

urlpatterns = [
	path('register/', register, name='register'),
	path('edit/', edit, name='edit'),
	path('', include('django.contrib.auth.urls')),
	path('', dashboard, name='dashboard'),
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView
from .schema import schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('graphql/', GraphQLView.as_view(schema=schema, graphiql=True))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from .views import image_create, image_detail, image_like, image_list

app_name = 'images'

urlpatterns = [
	path('', image_list, name='list'),
	path('create/', image_create, name='create'),
	path('detail/<id>/<slug>/', image_detail, name='detail'),
	path('like/', image_like, name='like'),
]

account/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	date_of_birth = models.DateTimeField(null=True, blank=True)
	photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

	def __str__(self):
		return self.user.username

images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='images_created')
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200, blank=True)
	url = models.URLField()
	image = models.ImageField(upload_to='images/%Y/%m/%d')
	description = models.TextField(blank=True)
	created = models.DateTimeField(auto_now_add=True, db_index=True)
	users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.title)
		super(Image, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('images:detail', kwargs={'id': self.id, 'slug': self.slug})

	def __str__(self):
		return self.title

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'username', 'email')

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError('Password mismatch.')
		return cd['password2']


class UserEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('date_of_birth', 'photo')

images/forms.py
from urllib import request

from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify

from .models import Image


class ImageForm(forms.ModelForm):
	class Meta:
		model = Image
		fields = ('title', 'url', 'description')
		widgets = {
			'url': forms.HiddenInput,
		}

	def clean_url(self):
		url = self.cleaned_data['url']
		valid_extensions = ('jpeg', 'jpg')
		extension = url.split('.')[-1].lower()
		if extension not in valid_extensions:
			raise forms.ValidationError('The given URL does not match valid image extensions.')
		return url

	def save(self, *args, commit=True, **kwargs):
		image_obj = super(ImageForm, self).save(commit=False)
		image_url = self.cleaned_data['url']
		image_name = "{}.{}".format(slugify(image_obj.title), image_url.split('.')[-1].lower())

		# download image
		response = request.urlopen(image_url)
		image_obj.image.save(image_name, ContentFile(response.read()), save=False)
		if commit:
			image_obj.save()
		return image_obj

account/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages

from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm
from .models import Profile


@login_required
def dashboard(request):
	return render(request, 'account/dashboard.html', {'section': 'Dashboard'})


def register(request):
	user_form = UserRegistrationForm()
	if request.method == 'POST':
		user_form = UserRegistrationForm(request.POST)
		if user_form.is_valid():
			cd = user_form.cleaned_data
			new_user = user_form.save(commit=False)
			new_user.set_password(cd['password'])
			new_user.save()
			Profile.objects.create(user=new_user)
			return render(request, 'account/register_done.html', {'new_user': new_user})

	return render(request, 'account/register.html', {'user_form': user_form})


@login_required
def edit(request):
	user_form = UserEditForm(instance=request.user)
	profile_form = ProfileEditForm(instance=request.user)
	if request.method == 'POST':
		user_form = UserEditForm(instance=request.user, data=request.POST)
		profile_form = ProfileEditForm(instance=request.user, data=request.POST, files=request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, 'Profile updated successfully')
		else:
			messages.error(request, 'Error updating your profile')
	return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from bookmarks.common.decorators import ajax_required

from .forms import ImageForm
from .models import Image


@login_required
def image_create(request):
	if request.method == 'POST':
		form = ImageForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			new_image = form.save(commit=False)
			new_image.user = request.user
			new_image.save()
			messages.success(request, 'Image added successfully')
			return redirect(new_image.get_absolute_url())
	else:
		form = ImageForm(request.GET)
		return render(request, 'images/image/create.html', {'form': form})


@login_required
def image_detail(request, id, slug):
	image = get_object_or_404(Image, slug=slug, id=id)
	return render(request, 'images/image/detail.html', {'image': image})


@ajax_required
@require_POST
@login_required
def image_like(request):
	image_id = request.POST.get('id', '')
	action = request.POST.get('action', '')
	if image_id and action:
		try:
			image = Image.objects.get(id=image_id)
			if action == 'like':
				image.users_like.add(request.user)
			else:
				image.users_like.remove(request.user)
			return JsonResponse({'status': 'ok'})
		except:
			pass
	return JsonResponse({'status': 'fail'})


@login_required
def image_list(request):
	images = Image.objects.all()
	paginator = Paginator(images, 10)
	page = request.GET.get('page')

	try:
		images = paginator.page(page)
	except PageNotAnInteger:
		images = paginator.page(1)
	except EmptyPage:
		if request.is_ajax():
			return HttpResponse('')
		images = paginator.page(paginator.num_pages)
	if request.is_ajax():
		return render(request, 'images/image/list_ajax.html', {'section': 'images', 'images': images})
	return render(request, 'images/image/list.html', {'section': 'images', 'images': images})

account/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<div id="header">
    <span class="logo">Bookmarks</span>
    {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == 'dashboard' %}class="selected"{% endif %}>
                <a href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li {% if section == 'images' %}class="selected"{% endif %}>
                <a href="{% url 'images:list' %}">Images</a>
            </li>
            <li {% if section == 'people' %}class="selected"{% endif %}>
                <a href="#">People</a>
            </li>
        </ul>
    {% endif %}
    <span class="user">
        {% if request.user.is_authenticated %}
            Hello {{ request.user.first_name }},
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Log-in</a>
        {% endif %}
    </span>
</div>
{% if messages %}
    <ul class="messages">
        {% for msg in messages %}
            <li class="{{ msg.tags }}">
                {{ msg|safe }} <a href="" class="close">✖</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous">
</script>
<script>
  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      let cookies = document.cookie.split(';');
      for (let i = 0; i < cookies.length; i++) {
        let cookie = jQuery.trim(cookies[i]);
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }

  let csrfToken = getCookie('csrftoken');

  function csrfSafeMethod(method) {
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }

  $.ajaxSetup({
    beforeSend: function (xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader('X-CSRFToken', csrfToken)
      }
    }
  });
  $(document).ready(function () {
    {% block domready %}
    {% endblock %}
  })
</script>
</html>

images/templates/images/image/create.html
{% extends 'base.html' %}

{% block title %}Bookmark an Image{% endblock %}

{% block content %}
    <h1>Bookmark an Image</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Bookmark image!">
    </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends 'base.html' %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
    <h1>{{ image.title }}</h1>
    {% load thumbnail %}
    {% thumbnail image.image '300' as im %}
        <a href="{{ image.image.url }}">
            <img src="{{ im.url }}" class="image-detail" alt="{{ image.title }}">
        </a>
    {% endthumbnail %}
    {% with total_likes=image.users_like.count users_like=image.users_like.all %}
        <div class="image-info">
            <div>
                <span class="count">
                    <span class="total">{{ total_likes }}</span> like{{ total_likes|pluralize }}
                </span>
                <a href="#" data-id="{{ image.id }}"
                   data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                    {% if request.user in users_like %}
                        Unlike
                    {% else %}
                        Like
                    {% endif %}
                </a>
            </div>
            {{ image.description|linebreaks }}
        </div>
        <div class="image-likes">
            {% for user in image.users_like.all %}
                {% if user.profile.photo %}
                    <img src="{{ user.profile.photo.url }}" alt="{{ user.first_name }}"> {{ user.first_name }}
                {% endif %}
                <br>
            {% empty %}
                <p>Be the first to like</p>
            {% endfor %}
        </div>
    {% endwith %}
{% endblock %}

{% block domready %}
      $('a.like').click(function (e) {
        e.preventDefault();
        $.post('{% url 'images:like' %}',
          {
            id: $(this).data('id'),
            action: $(this).data('action'),
          },
          function (data) {
            if (data['status'] == 'ok') {
              let previous_action = $('a.like').data('action')
              let previous_likes = parseInt($('span.count .total').text());
              $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
              $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
              $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
            }
          }
        );
      });
{% endblock %}

images/templates/images/image/list.html
{% extends 'base.html' %}

{% block title %}Bookmarked Images{% endblock %}

{% block content %}
    <h1>Bookmarked Images</h1>
    <div id="image-list">
        {% include 'images/image/list_ajax.html' %}
    </div>
{% endblock %}

{% block domready %}
      let page = 1;
      let emptyPage = false;
      let blockRequest = false;

      $(window).scroll(function () {
        let margin = $(document).height() - $(window).height() - 200;
        if ($(window).scrollTop() > margin && emptyPage === false && blockRequest === false) {
            blockRequest = true;
            page += 1;
            $.get('?page='+page, function (data) {
              if(data === ''){
                emptyPage = true;
              }else {
                blockRequest = false;
                $('#image-list').append(data)
              }
            })
        }
      })
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image '300x300' crop='100%' as im %}
                <a href="{{ image.get_absolute_url }}">
                    <img src="{{ im.url }}" alt="{{ image.title }}">
                </a>
            {% endthumbnail %}
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a>
        </div>
    </div>
{% empty %}
    <p>No Bookmarked images at the moment.</p>
{% endfor %}